export const FONT_LIST = [
    // Serif
    { value: 'Playfair Display', label: 'Playfair Display (Serif Elegan)', category: 'serif' },
    { value: 'Cinzel', label: 'Cinzel (Klasik Premium)', category: 'serif' },
    { value: 'Cinzel Decorative', label: 'Cinzel Decorative (Klasik Hiasan)', category: 'serif' },
    { value: 'Cormorant Garamond', label: 'Cormorant Garamond (Serif Tradisional)', category: 'serif' },
    { value: 'Marcellus', label: 'Marcellus (Serif Klasik Romawi)', category: 'serif' },
    { value: 'Prata', label: 'Prata (Serif Modern Kontras)', category: 'serif' },
    { value: 'Cardo', label: 'Cardo (Serif Buku Tua)', category: 'serif' },
    { value: 'Lora', label: 'Lora (Serif Lembut)', category: 'serif' },
    { value: 'Arapey', label: 'Arapey (Serif Vintage Tipis)', category: 'serif' },
    { value: 'Bodoni Moda', label: 'Bodoni Moda (Serif Kontras Tinggi)', category: 'serif' },
    { value: 'Gilda Display', label: 'Gilda Display (Serif Proporsional)', category: 'serif' },
    { value: 'Marcellus SC', label: 'Marcellus SC (Roman Small Caps)', category: 'serif' },

    // Script / Kaligrafi
    { value: 'Great Vibes', label: 'Great Vibes (Kaligrafi Tradisional)', category: 'script' },
    { value: 'Sacramento', label: 'Sacramento (Kaligrafi Minimalis)', category: 'script' },
    { value: 'Alex Brush', label: 'Alex Brush (Script Manis)', category: 'script' },
    { value: 'Allura', label: 'Allura (Script Anggun)', category: 'script' },
    { value: 'Dancing Script', label: 'Dancing Script (Script Ceria)', category: 'script' },
    { value: 'Parisienne', label: 'Parisienne (Script Romantis)', category: 'script' },
    { value: 'Pinyon Script', label: 'Pinyon Script (Script Mewah)', category: 'script' },
    { value: 'Rochester', label: 'Rochester (Script Klasik)', category: 'script' },
    { value: 'Italianno', label: 'Italianno (Kaligrafi Klasik)', category: 'script' },
    { value: 'Tangerine', label: 'Tangerine (Kaligrafi Tinggi Elegan)', category: 'script' },
    { value: 'Monsieur La Doulaise', label: 'Monsieur La Doulaise (Vintage Script)', category: 'script' },
    { value: 'Herr Von Muellerhoff', label: 'Herr Von Muellerhoff (Calligraphy Klasik)', category: 'script' },
    { value: 'Mrs Saint Delafield', label: 'Mrs Saint Delafield (Ornate Script)', category: 'script' },
    { value: 'Niconne', label: 'Niconne (Script Bulat Lembut)', category: 'script' },
    { value: 'Petit Formal Script', label: 'Petit Formal Script (Formal Script)', category: 'script' },
    { value: 'Yesteryear', label: 'Yesteryear (Script Retro)', category: 'script' },
    { value: 'Satisfy', label: 'Satisfy (Brush Script Modern)', category: 'script' },
    { value: 'WindSong', label: 'WindSong (Calligraphy Exotis)', category: 'script' },
    { value: 'Whisper', label: 'Whisper (Fine-line Script)', category: 'script' },
    { value: 'Cherish', label: 'Cherish (Script Lembut & Indah)', category: 'script' },
    { value: 'Meddon', label: 'Meddon (Tulisan Tangan Klasik)', category: 'script' },
    { value: 'La Belle Aurore', label: 'La Belle Aurore (Casual Handwriting)', category: 'script' },
    { value: 'Clicker Script', label: 'Clicker Script (Script Tipis)', category: 'script' },

    // Sans-serif
    { value: 'Inter', label: 'Inter (Sans-serif Bersih)', category: 'sans-serif' },
    { value: 'Montserrat', label: 'Montserrat (Modern Geometris)', category: 'sans-serif' },
    { value: 'Outfit', label: 'Outfit (Minimalis Premium)', category: 'sans-serif' },
    { value: 'Poppins', label: 'Poppins (Sans-serif Bulat)', category: 'sans-serif' },
    { value: 'Poiret One', label: 'Poiret One (Modern Art Deco)', category: 'sans-serif' },
    { value: 'Raleway', label: 'Raleway (Sans-serif Elegan)', category: 'sans-serif' },
    { value: 'Quicksand', label: 'Quicksand (Sans-serif Bulat Lembut)', category: 'sans-serif' },
    { value: 'Josefin Sans', label: 'Josefin Sans (Geometris Klasik)', category: 'sans-serif' },
    { value: 'Aboreto', label: 'Aboreto (Linear Space Modern)', category: 'sans-serif' }
];
